### PR TITLE
use le ordr

### PR DESCRIPTION
**Pull request by kpei**

### CODE REVIEW

**Comment by MasterIO02** [comment]
if this ever gets used please use the websocket instead of querying the o!rdr api every 5 seconds to know if the replay finished rendering. see https://ordr.issou.best/docs

**Review by christopher-dG — CHANGES_REQUESTED** [review]
Sorry, I'm not reviewing this until there are tests. They don't need to be e2e, you can mock out the actual ordr service.

**Comment by kpei** [comment]
@christopher-dG this should be ready. Can you help me with the github ci part, mainly in terms of setting up a proper test.sh file?

edit: should be all good 2 go

**Comment by christopher-dG** [comment]
Sorry, I don't really have time to review this for like a month. I'd estimate Sep 10-20 ish, feel free to ping me then if I still haven't gotten to it.

**Comment by kpei** [comment]
@christopher-dG bump

**Comment by MasterIO02** [comment]
bump? not sure if you're still in charge of osu-bot, but I'd really like to see it make renders again

**Comment by MasterIO02** [comment]
merging, will fix/change things in the main branch :ok_hand:

**Comment by MasterIO02** [comment]
should have squashed before merging, oops

**Pull request merged**
